# Generated by Django 2.1.7 on 2019-03-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_project_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('cost', models.IntegerField()),
                ('deadline', models.DateField()),
                ('possible_bugs', models.ManyToManyField(to='project_manager.Bug')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Completed'), ('2', 'In Progress')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Project'),
        ),
    ]
