# Generated by Django 2.1.7 on 2019-03-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20190314_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('change_password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('nid', models.IntegerField()),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('1', 'Married'), ('2', 'Unmarried')], default='2', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Completed'), ('2', 'In Progress')], default='2', max_length=1),
        ),
    ]
