# Generated by Django 2.1.7 on 2019-03-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_auto_20190316_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassign',
            old_name='possible_bugs',
            new_name='bugs',
        ),
    ]
