# Generated by Django 2.1.7 on 2019-03-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_auto_20190316_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.CharField(choices=[('1', 'Salary Deduction'), ('2', 'Overtime')], default='2', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='taskassign',
            name='request_id',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='requestforchange',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.TaskAssign'),
        ),
    ]
