# Generated by Django 2.1.7 on 2019-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_auto_20190318_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforchange',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
