# Generated by Django 2.1.7 on 2019-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0009_requestforchange_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
